---


- name: 'Restart SumoCollector'
  service:
    name: collector
    state: restarted
  when: ansible_os_family != "RedHat" and ansible_distribution_major_version != "7"
  tags: [sumologic, sumologic-collector]

# Workaround a bug with SysV scripts on a SystemD-based OS, with ansible 1.x.
# NOTE: A fix for this is in 2.x, so eventually it won't be needed
#   https://github.com/ansible/ansible-modules-core/commit/55e8863cb448a19ff4ee7f1f65b78c3a44893cee
- name: 'Restart SumoCollector - EL7'
  command: service collector restart
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  tags: [sumologic, sumologic-collector]
